//
// Created by Micha on 19.05.2024.
//

#ifndef POWERVR_VSGL_H
#define POWERVR_VSGL_H

typedef struct {

} SHAREDBLOCK;

#define VSGL_FREEBLOCK 1
#define VSGL_GETPHYSADDRESS 2
#define VSGL_ALLOCATEBLOCK 3
#define VSGL_FREEPHYSALIAS 4
#define VSGL_PAGE_REALLOCATE 5
#define VSGL_PAGE_FREE 6
#define VSGL_PAGE_COMMIT 7
#define VSGL_DISABLE_PHYSICAL_BOARD 8
#define VSGL_DESTROY_DMA_SCATTER_BUFFER 8
#define VSGL_ALLOC_VIRTUAL_PAGES 10
#define VSGL_GET_PHYSICAL_BOARD 11
#define VSGL_ENUM_PHYSICAL_BOARDS 12
#define VSGL_CREATE_DMA_SCATTER_BUFFER 13
#define VSGL_ENABLE_PHYSICAL_BOARD 14
#define VSGL_FREE_VIRTUAL_PAGES 15
#define VSGL_SETCACHEMODE 16
#define VSGL_COPYBUFFER 17
#define VSGL_SCHEDULE_RENDER 18
#define VSGL_SCHEDULER_LOCK 19
#define VSGL_SCHEDULER_UNLOCK 20
#define VSGL_GET_PHYSICAL_BOARD_INFO 21
#define VSGL_RELEASE_PHYSICAL_BOARD 22
#define VSGL_ALLOCPHYSALIAS 23
#define VSGL_PAGE_RESERVE 24

#endif //POWERVR_VSGL_H
